### ISSUE TITLE
[FEA] Would love a keyboard workflow

### ISSUE THREAD

**Issue by joedaniels29** [Zren/atom-open-recent#10]
Proposition: So, My usual IDE is intellij IDEA, and there, I have a keybinding `cmd-o,cmd-p` that opens a little UI in the center of the screen with my last 10 or so recent projects. I can then quickly navigate the list with the keyboard and open other projects in like a second. I'm not super familiar with the atom programming model so I'm not sure I could do this myself, but this would be a cool feature to have. Maybe the ui could look something like the actions search (the one you get with `cmd-shift-p` ? )

**Comment by Zren** [comment]
Currently ![](http://i.imgur.com/LAsE6c7.png) show up if you type `open recent` in the command palette. Unfortunately there's no simple way to show a nice menu there (the titles are auto generated by the event name and there's no way to override it). I could do a submenu with only the recent files + directories though, but that's 2 menues you'd need to navigate unless you bind it to some keybinding.

**Comment by Zren** [comment]
As mentioned by @xnat9 in #15, this feature is possible.

![](http://i.imgur.com/irFjnIR.png)

It's likely that there will be a horizontal scrollbar in the command palette if I do this since most paths are fairly long.

![](http://i.imgur.com/Vj19qxx.png)

**Comment by Zren** [comment]
Implemented it. I don't really like how Clear is the top option though.

![](http://i.imgur.com/4EveBFI.png)

Edit: Did [a hack](http://i.imgur.com/A1FwPke.png) to sort Clear at the bottom. I added 1024 `-` which translate to spaces, making the string longer. I tried using `Z`/`z`/`{` as prefixes but it didn't matter so alphabetical/ascii is ignored in fuzzysearch.

**Comment by Zren** [comment]
Added in v5.0.0.
