### ISSUE TITLE
can add config option?

### ISSUE THREAD

**Issue by xnat9** [Zren/atom-open-recent#15]
can add a option that can show path in command not index:
atom.commands.add "atom-workspace", "open-recent:open-path-#{index}"
atom.commands.add "atom-workspace", "open-recent:open-path-#{path}"

a option that can open a recent path in current window:
atom.project.addPath(path)
      # atom.open {
      #   pathsToOpen: [path]
      #   newWindow: !atom.config.get('open-recent.replaceNewWindowOnOpenDirectory')
      # }

**Comment by Zren** [comment]
This is similar to #10 (show path in the command palette menu)? This would require serializing the path is a clean format (lowercase & convert non alphanumeric characters to dashes) and make sure there's no duplicates. Actually I could probably do `"open-recent:open-path-#{index}-#{cleanPath(path)}"` to make the command keys unique. It will still look like `Open Recent: Open Path 1 C File Txt` with the path `C:\File.txt` which doesn't look very good. Last time I checked, there's no way to override the command palette title for a command.

> a option that can open a recent path in current window:

?

**Comment by xnat9** [comment]
this follow function can resolve "C:\File.txt" path.
convertPath: (path) ->
    path.replace(/(:\|\)/g, "/")

**Comment by Zren** [comment]
`\`'s don't need to be replaced, just `:` and `-` since `:` is used to format the namespace (all characters after the second `:` are ignored) and `-` is replaced with a space and the next letter is capitalized.

So:

``` coffee
encodeEventName: (s) ->
  s = s.replace('-', '\u2010') # HYPHEN
  s = s.replace(':', '\u02D0') # MO­DI­FI­ER LET­TER TRIANGULAR COLON
  return s

console.log(encodeEventName("C:\\File.txt")) # 
console.log(encodeEventName("C:\\Users\\Admin\\.atom\\packages\\open-recent\\lib\\main.coffee"))
```

![](http://i.imgur.com/irFjnIR.png)

Huh, it actually worked well. Obviously it won't be able to match `:` and `-` since we replace them, but it's worthwhile adding.

**Comment by Zren** [comment]
Anyways closing this issue as duplicate.
