### ISSUE TITLE
Empty items in menu

### ISSUE THREAD

**Issue by jerone** [Zren/atom-open-recent#16]
I noticed an empty item in the folders and files Open Recent menu. While investigating I came across an [error](https://github.com/jerone/menu-manager/issues/3) with my Menu Manager package, as a result of this issue. The problem is that after getting the list of recent items from the localStorage, an extra item is append to both lists, both called `open-recent:open-recent-file-unique` (notice the word `unique` instead of an number). Also this item is not included in the localStorage. The extra item is empty with the exception of the `label`, which is a function.

Apparently in the [`for .. of` loop](https://github.com/Zren/atom-open-recent/blob/master/lib/main.coffee#L224) an function called `unique` is also processed. Any idea why?

**Comment by jerone** [comment]
As you're using an array as data you probably should use `for .. in` or `for own .. of` for [looping](http://coffeescript.org/#loops).

Still don't know where this `unique` function is coming from, some package is probably extending the `Array.prototype`. :(

**Comment by jerone** [comment]
[Linked](https://github.com/lexicalunit/linter-just-say-no/issues/7) the [custom function](https://github.com/lexicalunit/linter-just-say-no/blob/d7c97520658cd78c3d581cf38785d36d9e30457d/lib/linter-just-say-no-provider.coffee#L1) to the "Linter Just Say No" package.

**Comment by Zren** [comment]
Pretty easy to confirm. Just had to add `Array.prototype.unique = -> return []` at the top of my file.
