### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jerone** [Zren/atom-open-recent#2]
Hey @Zren, got a bug report for you with the new Atom:

> atom.workspaceView is no longer available.
> In most cases you will not need the view. See the Workspace docs for
> alternatives: https://atom.io/docs/api/latest/Workspace.
> If you do need the view, please use `atom.views.getView(atom.workspace)`,
> which returns an HTMLElement.
> 
> ```
> Atom.Object.defineProperty.get (c:\Users\xxx\AppData\Local\atom\app-0.174.0\resources\app\src\atom.js:55:11)
> <unknown> (c:\Users\xxx\.atom\packages\open-recent\lib\main.coffee:46:11)
> ```

Hope you can fix it.

**Comment by Zren** [comment]
Didn't realize you used atom @jerone. Thanks for the report.

**Comment by jerone** [comment]
Since a few weeks now. Wouldn't be using it if it wasn't for this package! Very useful. Thnx for fixing.
