### ISSUE TITLE
Deprecation Cop warnings

### ISSUE THREAD

**Issue by xeron** [Zren/atom-open-recent#5]
open-recent (2 deprecations):
Call ::getActiveTextEditor instead
Called 4 times

```
Workspace.getActiveEditor - /Applications/Atom.app/Contents/Resources/app/src/workspace.js:999:12
[object Object].onUriOpened - /Users/xeron/.atom/packages/open-recent/lib/main.coffee:32:26
```

Use ::getDirectories instead
Called 1 time

```
Project.getRootDirectory - /Applications/Atom.app/Contents/Resources/app/src/project.js:593:12
[object Object].insertCurrentPaths - /Users/xeron/.atom/packages/open-recent/lib/main.coffee:136:29
```

Also open-recent affects atom-core:

atom core (1 deprecation):
Use a config schema instead. See the configuration section of https://atom.io/docs/latest/hacking-atom-package-word-count and https://atom.io/docs/api/latest/Config for more details
Called 1 time

```
Package.activateConfig - /Applications/Atom.app/Contents/Resources/app/src/package.js:250:11
Package.activateNow - /Applications/Atom.app/Contents/Resources/app/src/package.js:221:14
```

Related to https://github.com/atom/atom/issues/6310, disabling open-recent removes this warning.

**Comment by Zren** [comment]
To non sleepy self:
1. Simple rename
2. `getDirectories().length`
3. Change `configDefaults` to `config` and do `{ type: 'number', default: 123 }` instead.
