### ISSUE TITLE
'Installing "open-recent@2.2.4" failed.'

### ISSUE THREAD

**Issue by rummelsworth** [Zren/atom-open-recent#7]
I tried installing v2.2.4 via the Settings / Install page in Atom 0.208.0 on Windows 7 Pro 64-bit, and the first install seemed to hang/fail with this error. I installed again and this time it seemed to work fine. I then went over to the installed packages list and it showed this error, which I guess happened during the first install:

![open-recent-2 2 4-install-error](https://cloud.githubusercontent.com/assets/3069355/8090015/0689b742-0f71-11e5-997b-bb625e2a94c0.PNG)

The README.md file is there, I checked. Maybe the installer tries to open it before it's actually available from the filesystem, so the second install found it without a problem because the first install had already put it there?

**Comment by Zren** [comment]
Does deleting `C:\Users\wrummler\.atom\packages\open-recent` then reinstalling work?

**Comment by rummelsworth** [comment]
Yep, that works. I tried again from scratch and can't reproduce the issue... Well, if it happens again, I'll comment again. Feel free to close unless you want me to try some other specific things to try to reproduce it. Btw, thanks for the quick response and for maintaining this package.

**Comment by Zren** [comment]
Mmmmk, seems like a failed install. Glad that solved it.
